### ISSUE TITLE
keycloack not starting up

### ISSUE THREAD

**Issue by hmontazeri** [gematik/DEMIS-Test_Environment#2]
![image](https://user-images.githubusercontent.com/1557035/173823014-f0228a96-dae8-46e0-ae38-cbf6e0b87765.png)

Hey all,

any ideas why it freezes while starting up keycloak? 
Could it have anything to do with apple m1?

**Comment by Gematik-DEMIS** [comment]
Hey,

please check the log of demis-kecloak container by issuing following command:

`docker logs demis-keycloak`

If you need further assistance, please drop us an email with the result of this command to [demis@gematik.de](mailto:demis@gematik.de).

Regards,

gematik DEMIS Development Team

**Comment by hmontazeri** [comment]
It is in fact an Apple Silicon (M1) problem with JBOSS. 

It runs smooth on my intel machine. Just heads up for further updates.
