### ISSUE TITLE
nginx.truststore does not contain the latest certificates.

### ISSUE THREAD

**Issue by ElrondMacBong** [gematik/DEMIS-Test_Environment#3]
The nginx.truststore from DEMIS-Importer, does not contain the latest certificates. When fetching test messages, the message appears:

unable to find valid certification path to requested target

**Comment by AroukX** [comment]
Hello @ElrondMacBong, thank you for the hint. We will fix the issue with the next release. This will happen tomorrow.

**Comment by ElrondMacBong** [comment]
now it's working, thank you.
